routes/web.php
<?php
// SUB-DOMAIN E-NIAGA 
Route::domain('eniaga.'.env('APP_URL'))->group(function () {
  Route::get('/', function () {
      return view('soon');
  })->name('eniaga.index');
});
// PUBLIC ROUTES
Route::get('/', 'HomeController@index')->name('beranda');
Route::get('/struktur-organisasi', 'HomeController@struktur')->name('struktur');
Route::get('/sejarah', 'HomeController@sejarah')->name('sejarah');
Route::get('/potensi','HomeController@potensi'); 
Route::get('/artikel', 'HomeController@artikel')->name('artikel');
Route::get('/artikel/{name}', 'HomeController@lihat_artikel')->name('artikel.lihat');
Route::get('/galeri', 'HomeController@galeri')->name('galeri');
Route::get('/galeri/{content}/{name}', 'HomeController@lihat_album')->name('galeri.lihat');
Route::get('/produk-hukum/{name?}', 'HomeController@hukum')->name('produk-hukum');
Route::get('/pelayanan', 'HomeController@service')->name('pelayanan');
Route::get('/pelayanan/{name}', 'HomeController@services')->name('pelayanan.index');
Route::post('/propose_service', 'HomeController@propose_service')->name('propose_service.store');
Route::get('/infografik','HomeController@infografik');
Route::get('/apbdesa', 'HomeController@apbdesa')->name('apbdesa');
Route::get('/soon', function(){
  return view('soon');
})->name('soon');

// PUBLIC ROUTES --services--
Route::get('/pelayanan', 'HomeController@service')->name('pelayanan');
Route::get('/pelayanan/{name}', 'HomeController@services')->name('pelayanan.index');
Route::post('/propose_service', 'HomeController@propose_service')->name('propose_service.store');
Route::get('/propose_service', 'HomeController@propose_service')->name('propose_service');
Route::get('/trace_service', 'HomeController@trace_service')->name('trace_service');
Route::post('/trace_services', 'HomeController@trace_services')->name('trace_services');


Route::resource('/post', 'PostController');
Route::get('/posts', 'PostController@list')->name('posts');

Route::resource('/tag', 'TagController');
Route::resource('/apparatus', 'ApparatusController');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/{nama}', 'HomeController@show');

Route::resource('/type', 'TypeController');
Route::get('/types', 'TypeController@list')->name('types');

Route::resource('/profile', 'ProfileController');
Route::get('profil/{name}', 'ProfileController@profil');
// Route::get('profil/{name}', 'ProfileController@struktur');

Route::resource('/gallery', 'GalleryController');
Route::get('/gallery/content/{gallery}/{id}', 'GalleryController@content')->name('gallery.content');
Route::get('/galleries/{content}', 'GalleryController@list')->name('galleries');
Route::post('/gallery/store_content', 'GalleryController@store_content')->name('gallery.store_content');
Route::get('/gallery/edit/{gallery}/{id}', 'GalleryController@edit')->name('gallery.edit');
Route::put('/gallery/update/{id}', 'GalleryController@update')->name('gallery.update');

Route::resource('/population', 'PopulationController');
Route::get('/population/list/{id}', 'PopulationController@list')->name('populations.list');
Route::get('/populations', 'PopulationController@list')->name('populations');
Route::post('/population/get_population/{id}', 'ServicingController@get_population')->name('get_population');

Route::resource('/education', 'EducationController');
Route::get('/educations', 'EducationController@list')->name('educations');

Route::resource('/occupation', 'OccupationController');
Route::get('/occupations', 'OccupationController@list')->name('occupations');

Route::resource('/facility', 'FacilityController');
Route::get('/facilitys', 'FacilityController@list')->name('facilitys');

// ---------------------------- API services ----------------------------
/* servicings/value/field */
Route::get('/servicing/servicings/{id}/{name}', 'ServicingController@servicings')->name('servicings');

//services list Routes
Route::get('/servicing/new', 'ServicingController@new')->name('new');
Route::get('/servicing/create_new', 'ServicingController@new_create')->name('new.create');
Route::get('/servicing/show_new/{id}', 'ServicingController@new_show')->name('new.show');
Route::put('/servicing/update_new/{id}', 'ServicingController@new_update')->name('new.update');
Route::get('/servicing/edit_new/{id}', 'ServicingController@new_edit')->name('new.edit');
Route::get('/servicing/verify_new/{id}', 'ServicingController@new_verify')->name('new.verify');
Route::get('/servicing/news/', 'ServicingController@news')->name('news');
Route::post('/servicing/store_new', 'ServicingController@new_store')->name('new.store');
Route::delete('/servicing/delete_new/{id}', 'ServicingController@new_delete')->name('new.delete');

// services process list route
Route::get('/servicing/process_service', 'ServicingController@process_service')->name('process_service');
Route::get('/servicing/process_services', 'ServicingController@process_services')->name('process_services');
Route::get('/servicing/process_verify/{id}', 'ServicingController@process_verify')->name('process.verify');

// services done list route
Route::get('/servicing/done_service', 'ServicingController@done_service')->name('done_service');
Route::get('/servicing/done_services', 'ServicingController@done_services')->name('done_services');

// counter notify services
Route::get('/servicing/counter_services/{name}', 'ServicingController@counter_services')->name('counter_services');

Route::prefix('potency')->group(function(){
  Route::resource('criteria', 'CriteriaController');
  Route::get('/criteria/branch/{id}', 'CriteriaController@branch')->name('criteria.branch');
  Route::post('/criteria/store_new', 'CriteriaController@new_store')->name('criteria.store_new');  
  Route::get('/criteria/detail_tabulations/{id}', 'CriteriaController@detail_tabulations')->name('criteria.detail_tabulations');  
});

// PRODUK HUKUM
Route::resource('/juristical', 'JuristicalController')->except(['destroy', 'show']);
Route::get('/juristicals', 'JuristicalController@list')->name('juristicals');

// E-NIAGA
Route::prefix('eniaga')->group(function(){});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = 'posts';
    protected $guarded = [];
    protected $fillable = [];
    // protected $hidden = [];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function type()
    {
        return $this->belongsTo('App\Type');
    }

    public function tags()
	{
		return $this->morphToMany(Tag::class, 'taggable');
	}
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use App\Post;
use App\Type;
use App\Tag;
use Carbon\Carbon;

class PostController extends Controller
{
    private $allowedImage = [
        'image/jpeg',
        'image/png',
    ];

    public function __construct()
    {
        $this->middleware('auth')->except(['list']);
    }

    public function index()
    {
        return view('posts.index');
    }

    public function show($id)
    {
        $post = Post::findOrFail($id);
            // ->with(['tags' => function($q){
            //     $q->select('name');
            // }])
            // ->first();
        
        $tags = $post->tags->map(function($tag){
            return [
                'name' => $tag->name
            ];
        });

        $query = [
            'id' => $post->id,
            'name' => $post->name,
            'body' => $post->body,
            'type' => $post->type->name,
            'user' => $post->user->name,
            'tags' => $tags
        ];

        // dd($query);
        // return $post->tags;
        return response()->json($query);
    }

    public function create()
    {
        $types = Type::all();
        $tags = Tag::select('id', 'name')->get();
        
        return view('posts.create', compact('types', 'tags'));
    }

    public function store(Request $request)
    {
        $data = $this->validate($request, [
            'type_id' => 'required',
            'name' => 'required|max:191',
            'image' => 'required',
            'body' => 'required',
        ]);
        // test user
        $data['user_id'] = Auth::id();
        $data['created_at'] = Carbon::now(); 
        $data['updated_at'] = Carbon::now();       

        if($request->active == null){
            $data['active'] = '0';
        }else{
            $data['active'] = '1';
        }

        if($request->hasFile('image')){
            $extension = $request->image->getMimeType();
            if (! in_array($extension, $this->allowedImage)) {
                return back()->withInput()->withErrors(array('image' => 'Tipe file tidak di dukung.'));
            }else{
                $date = date('ymdhis_');
                $file = $request->image->getClientOriginalName();
                $filename = $date . str_replace(' ', '_', strtolower($file));
                $store = $request->image->storeAs('public/images', $filename);
                $data['image'] = $filename;
            }
        }

        $post = Post::insertGetId($data);
        if(!$post){
            return back()->with('alert-danger', 'Artikel tidak dapat di simpan.');
        }

        $count = count($request->tags);
        if($count > 0){
            $postId = Post::find($post);
            $postId->tags()->attach($request->tags);
        }
        // dd($request->tags);
        return redirect()->route('post.index')->with('alert-info', 'Artikel telah di simpan.');
    }

    public function edit($id)
    {
        $data = Post::findOrFail($id);
        $types = Type::all();
        $tags = Tag::select('id', 'name')->get();
        
        // dd($data->tags);
        return view('posts.edit', compact('data', 'types', 'tags'));
    }

    public function update(Request $request, $id)
    {
        $post = Post::find($id);

        $data = $this->validate($request, [
            'type_id' => 'required',
            'name' => 'required|max:191',
            'image' => '',
            'body' => 'required',
        ]);
        
        $data['updated_at'] = Carbon::now();

        if($request->active == null){
            $data['active'] = '0';
        }else{
            $data['active'] = '1';
        }

        if($request->hasFile('image')){
            $extension = $request->image->getMimeType();
            if (! in_array($extension, $this->allowedImage)) {
                return back()->withInput()->withErrors(array('image' => 'Tipe file tidak di dukung.'));
            }else{
                $date = date('ymdhis_');
                $file = $request->image->getClientOriginalName();
                $filename = $date . str_replace(' ', '_', strtolower($file));
                $store = $request->image->storeAs('public/images', $filename);
                $data['image'] = $filename;
            }
        }

        if(!$post->tags()->sync($request->tags)){
            return back()->with('alert-danger', 'Data kategori tidak dapat di update.');
        }

        if(!$post->update($data)){
            return back()->with('alert-danger', 'Artikel tidak dapat di update.');
        }

        return redirect()->route('post.index')->with('alert-info', 'Artikel telah di update.');
    }

    public function destroy($id)
    {
      $post = Post::find($id);
      $post->delete();
      // return suksesRedirect::back()->with('message','Menghapus data berhasil !');
      return response()->json(['message' => 'success'], 200);
    }

    public function list()
    {
        $posts = Post::orderBy('updated_at', 'desc')->get();
        $data = $posts->map(function($item){
            if($item->active !== 0){
                $active = 'checked';
            }else{
                $active = '';
            }
            return [
                'id' => $item->id,
                'type' => $item->type->name,
                'name' => $item->name,
                'active' => $active,
                'created' => $item->updated_at->format('d-m-Y')
            ];
        });
        return response()->json($data);
    }
}

resources/views/posts/create.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- TITLE -->
<section class="welcome p-t-10">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="title-5">BUAT ARTIKEL</h3>
        <hr class="line-seprate">
      </div>
    </div>
  </div>
</section>
<!-- SECTION BODY -->
<section class="statistic-chart">
  <div class="container">
    <form action="{{route('post.store')}}" method="post" class="row" enctype="multipart/form-data">
      {{csrf_field()}}
      <div class="col-md-6">
        {{-- NAME --}}
        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
          <label class="form-control-label">Judul</label>
          <input type="text" name="name" placeholder="Isi Judul..." value="{{ old('name') }}" class="form-control">
          @if ($errors->has('name'))
            <small class="form-text text-danger">{{ $errors->first('name') }}</small>
          @endif
        </div>
        {{-- TYPE & STATUS --}}
        <div class="row">
          <div class="form-group col-md-6">
            <label class="form-control-label">Tipe</label>
            <div class="select">
              <select name="type_id" class="form-control">
                <option selected disabled value="">Pilih Tipe</option>
                @foreach ($types as $item)
                  <option value="{{ $item->id }}">{{ $item->name }}</option>
                @endforeach
              </select>
              @if ($errors->has('type_id'))
                <small class="form-text text-danger">{{ $errors->first('type_id') }}</small>
              @endif
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-control-label">Status Aktif</div>
            <label class="switch switch-text switch-success mt-3">
              <input id="poststatus" type="checkbox" name="active" class="switch-input" checked>
              <span data-on="On" data-off="Off" class="switch-label"></span>
              <span class="switch-handle"></span>
            </label>
          </div>
        </div>
        {{-- TAGS --}}
        <label for="multiple-select" class=" form-control-label">Kategori</label>
        <select name="tags[]" id="multiple-select" multiple="" class="">
          @foreach($tags as $item)
            <option value="{{$item->id}}">{!! $item->name !!}</option>
          @endforeach
        </select>
      </div>
      <div class="col-md-6">
        {{-- IMAGES --}}
        <div class="form-group{{ $errors->has('image') ? ' has-danger' : '' }}">
          <label class="form-control-label">Foto Banner</label>
          <img id="imageFile01" src="{{asset('storage\images\no-img.png')}}" class="img-fluid mx-auto d-block mb-3" alt="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
            </div>
            <div class="custom-file">
              <input 
                type="file" 
                class="custom-file-input" 
                id="inputGroupFile01" 
                name="image"
                accept="image/png, image/jpeg" 
                aria-describedby="inputGroupFileAddon01">
              <label class="custom-file-label" for="inputGroupFile01"></label>
            </div>
          </div>
          @if ($errors->has('image'))
            <small class="form-text text-danger">{{ $errors->first('image') }}</small>
          @endif
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <label class="form-control-label">Isi Artikel :</label>
          <div id="body" style="background-color: #fff; height: 400px;"></div>
          <input type="hidden" name="body">
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary">Simpan</button>
    </form>
  </div>
</section>  
@endsection

@push('scripts')
<script>
  $(document).ready(function(){
    $('input[type="file"]').change(function(e) {
      var filename = e.target.files[0].name;
      $('.custom-file-label').text(filename);

      var reader = new FileReader();
      reader.onload = function (e) {
        $('#imageFile01').attr('src', e.target.result);
      }
      reader.readAsDataURL(this.files[0]);
    });
  });

  var multi = new SlimSelect({
    select: '#multiple-select'
  })

  var quill = new Quill('#body',{
    modules: {
      toolbar: QuilljsToolbarOptions,
    },
    theme: 'snow',
    placeholder: '...'
  });

  $('form').submit(function(e){
    cfg = {};
    cek = quill.getContents().ops;
    convert = new QuillDeltaToHtmlConverter(cek, cfg).convert();
    $('input[name="body"]').val(convert);
  });
</script>
@endpush

resources/views/posts/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- TITLE -->
<section class="welcome p-t-10">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="title-5">EDIT ARTIKEL</h3>
        <hr class="line-seprate">
      </div>
    </div>
  </div>
</section>
<!-- SECTION BODY -->
<section class="statistic-chart">
  <div class="container">
    <form action="{{route('post.update', $data->id)}}" method="post" class="row" enctype="multipart/form-data">
      {{csrf_field()}}
      <input type="hidden" name="_method" value="PUT">
      <div class="col-md-6">
        {{-- NAME --}}
        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
          <label class="form-control-label">Judul</label>
          <input type="text" name="name" placeholder="Isi Judul..." value="{{ old('name', $data->name) }}" class="form-control">
          @if ($errors->has('name'))
            <small class="form-text text-danger">{{ $errors->first('name') }}</small>
          @endif
        </div>
        {{-- TYPE & STATUS --}}
        <div class="row">
          <div class="form-group col-md-6">
            <label class="form-control-label">Tipe</label>
            <div class="select">
              <select name="type_id" class="form-control">
                <option selected disabled value="">Pilih Tipe</option>
                @foreach ($types as $item)
                  <option {{ $data->type_id == $item->id ? 'selected' : '' }} value="{{ $item->id }}">{{ $item->name }}</option>
                @endforeach
              </select>
              @if ($errors->has('type_id'))
                <small class="form-text text-danger">{{ $errors->first('type_id') }}</small>
              @endif
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-control-label">Status Aktif</div>
            <label class="switch switch-text switch-success mt-3">
              <input type="checkbox" name="active" value="{{$data->active}}" class="switch-input" {{$data->active == true ? 'checked' : ''}}>
              <span data-on="On" data-off="Off" class="switch-label"></span>
              <span class="switch-handle"></span>
            </label>
          </div>
        </div>
        {{-- TAGS --}}
        <label for="multiple-select" class=" form-control-label">Kategori</label>
        <select name="tags[]" id="multiple-select" class="" multiple>
          @foreach($tags as $item)
            <option 
              value="{{$item->id}}" 
              {{
                collect($data->tags)
                  ->pluck('name')
                  ->contains($item->name) == 1 ? 'selected' : ''
              }}>{!! $item->name !!}</option>
          @endforeach
        </select>
      </div>
      <div class="col-md-6">
        {{-- IMAGES --}}
        <div class="form-group{{ $errors->has('image') ? ' has-danger' : '' }}">
          <label class="form-control-label">Foto Banner</label>
          <img id="imageFile01" src="{{asset('storage\images\\'.$data->image)}}" class="img-fluid mx-auto d-block mb-3" alt="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputFileAddon01">Upload</span>
            </div>
            <div class="custom-file">
              <input
                type="file" 
                class="custom-file-input" 
                id="inputFile01" 
                name="image"
                accept="image/png, image/jpeg"
                aria-describedby="inputFileAddon01">
              <label class="custom-file-label" for="inputFile01">{!! $data->image !!}</label>
            </div>
          </div>
          @if ($errors->has('image'))
            <small class="form-text text-danger">{{ $errors->first('image') }}</small>
          @endif
        </div>
      </div>
      <div class="col-md-12">
        {{-- BODY --}}
        <div class="form-group">
          <label class="form-control-label">Isi Artikel :</label>
          <div id="body" style="background-color: #fff; height: 400px;">
            {!! old('body',$data->body) !!}
          </div>
          <input type="hidden" name="body">
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary">Simpan</button>
    </form>
  </div>
</section>  
@endsection

@push('scripts')
<script>  
  $(document).ready(function(){
    $('input[type="file"]').change(function(e) {
      var filename = e.target.files[0].name;
      $('.custom-file-label').text(filename);

      var reader = new FileReader();
      reader.onload = function (e) {
        $('#imageFile01').attr('src', e.target.result);
      }
      reader.readAsDataURL(this.files[0]);
    });
  });

  var multi = new SlimSelect({
    select: '#multiple-select'
  })
  
  var quill = new Quill('#body',{
    modules: {
      toolbar: QuilljsToolbarOptions
    },
    theme: 'snow',
    placeholder: '...'
  });

  content = $("#body").find(".ql-editor p").html();
  if(isJson(content) == true){
    quill.setContents(JSON.parse(quill.getContents().ops[0].insert))
  }

  $('form').submit(function(e){
    cfg = {};
    cek = quill.getContents().ops;
    convert = new QuillDeltaToHtmlConverter(cek, cfg).convert();
    $('input[name="body"]').val(convert);
  });
</script>
@endpush

resources/views/posts/index.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- TITLE -->
<section class="welcome p-t-10">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="title-5">DAFTAR BERITA</h3>
        <hr class="line-seprate">
      </div>
    </div>
  </div>
</section>
<!-- SECTION BODY -->
<section class="statistic-chart">
  <div class="container">
    <div class="row">
      <!-- DATA TABLE-->  
      <div class="col-md-12">
        <div class="table-responsive m-b-40">
          <div class="table-data__tool">
            <div class="table-data__tool-left">
            <a href="{{route('post.create')}}" class="btn btn-info mt-2 ml-5">Tambah Berita</a>
            </div>
          </div>
          {{-- <table id="posttable"> --}}
          <table id="posttable" class="table table-borderless table-data3">
            <thead>
              <tr>
                <th>ID</th>
                <th>tanggal</th>
                <th>tipe</th>
                <th>judul</th>
                <th>Aktif</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
      <!-- Button trigger modal -->
      {{-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Launch demo modal
      </button> --}}
      {{-- <canvas id="tesChart"></canvas> --}}
    </div>
  </div>
</section>
<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam laborum quas laudantium repellat? Veniam, porro voluptates accusamus aut exercitationem rem facere, tempora molestias odio quam obcaecati et, eos recusandae beatae!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consectetur, voluptate similique? Nemo delectus, quae magnam odio culpa nesciunt! Nam necessitatibus molestiae assumenda maxime odit explicabo atque ducimus placeat, repellat voluptatem?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur consectetur voluptatum alias aperiam nam impedit ea quasi optio eius, odit quisquam eveniet sunt incidunt perspiciatis sed corporis. Ducimus, quod cum.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

@endsection

@push('scripts')
<script>
  $("#posttable").DataTable({
    scrollY: "320px",
    scrollCollapse: true,
    paging: false,
    ordering: false,
    ajax: {
      url: '{{ route('posts') }}',
      dataSrc: '',
    },
    // order: [[ 1, "desc" ]],
    columns: [
      {data: 'id'},
      {data: 'created'},
      {data: 'type'},
      {data: 'name'},
    ],
    columnDefs: [
      {
        targets: [ 0 ],
        visible: false,
        searchable: false
      },
      {
        targets: [ 4 ],
        data: 'active',
        render: function ( data, type, row, meta ) {
          return `
            <label class="au-checkbox">
              <input type="checkbox" `+data+`>
              <span class="au-checkmark"></span>
            </label>`;
        }
      },
      {
        targets: [5],
        data: 'id',
        render: function ( data, type, row, meta ) {
          return '<a href="post/'+data+'/edit" class="btn">edit</a><a href="#!" data-id="'+data+'" class="btn delete-post">delete</a>';
        }
      }
    ]
  });
  $(document).on('click', '.delete-post', function(e){
    // e.preventDefault();
    id = $(this).data('id');
    r = confirm('Anda yakin akan menghapus data..?');
    if(r==true){
      $.ajax({
        type: 'DELETE',
        url: '/post/'+id,
        dataType: 'json',
        data: {
          '_token': $('meta[name="csrf-token"]').attr('content'),
        },
        success: function () {
          window.location.reload()
        }
      })
    }
  });
</script>
@endpush