routes/web.php
<?php
// SUB-DOMAIN E-NIAGA 
Route::domain('eniaga.'.env('APP_URL'))->group(function () {
  Route::get('/', function () {
      return view('soon');
  })->name('eniaga.index');
});
// PUBLIC ROUTES
Route::get('/', 'HomeController@index')->name('beranda');
Route::get('/struktur-organisasi', 'HomeController@struktur')->name('struktur');
Route::get('/sejarah', 'HomeController@sejarah')->name('sejarah');
Route::get('/potensi','HomeController@potensi'); 
Route::get('/artikel', 'HomeController@artikel')->name('artikel');
Route::get('/artikel/{name}', 'HomeController@lihat_artikel')->name('artikel.lihat');
Route::get('/galeri', 'HomeController@galeri')->name('galeri');
Route::get('/galeri/{content}/{name}', 'HomeController@lihat_album')->name('galeri.lihat');
Route::get('/produk-hukum/{name?}', 'HomeController@hukum')->name('produk-hukum');
Route::get('/pelayanan', 'HomeController@service')->name('pelayanan');
Route::get('/pelayanan/{name}', 'HomeController@services')->name('pelayanan.index');
Route::post('/propose_service', 'HomeController@propose_service')->name('propose_service.store');
Route::get('/infografik','HomeController@infografik');
Route::get('/apbdesa', 'HomeController@apbdesa')->name('apbdesa');
Route::get('/soon', function(){
  return view('soon');
})->name('soon');

// PUBLIC ROUTES --services--
Route::get('/pelayanan', 'HomeController@service')->name('pelayanan');
Route::get('/pelayanan/{name}', 'HomeController@services')->name('pelayanan.index');
Route::post('/propose_service', 'HomeController@propose_service')->name('propose_service.store');
Route::get('/propose_service', 'HomeController@propose_service')->name('propose_service');
Route::get('/trace_service', 'HomeController@trace_service')->name('trace_service');
Route::post('/trace_services', 'HomeController@trace_services')->name('trace_services');


Route::resource('/post', 'PostController');
Route::get('/posts', 'PostController@list')->name('posts');

Route::resource('/tag', 'TagController');
Route::resource('/apparatus', 'ApparatusController');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/{nama}', 'HomeController@show');

Route::resource('/type', 'TypeController');
Route::get('/types', 'TypeController@list')->name('types');

Route::resource('/profile', 'ProfileController');
Route::get('profil/{name}', 'ProfileController@profil');
// Route::get('profil/{name}', 'ProfileController@struktur');

Route::resource('/gallery', 'GalleryController');
Route::get('/gallery/content/{gallery}/{id}', 'GalleryController@content')->name('gallery.content');
Route::get('/galleries/{content}', 'GalleryController@list')->name('galleries');
Route::post('/gallery/store_content', 'GalleryController@store_content')->name('gallery.store_content');
Route::get('/gallery/edit/{gallery}/{id}', 'GalleryController@edit')->name('gallery.edit');
Route::put('/gallery/update/{id}', 'GalleryController@update')->name('gallery.update');

Route::resource('/population', 'PopulationController');
Route::get('/population/list/{id}', 'PopulationController@list')->name('populations.list');
Route::get('/populations', 'PopulationController@list')->name('populations');
Route::post('/population/get_population/{id}', 'ServicingController@get_population')->name('get_population');

Route::resource('/education', 'EducationController');
Route::get('/educations', 'EducationController@list')->name('educations');

Route::resource('/occupation', 'OccupationController');
Route::get('/occupations', 'OccupationController@list')->name('occupations');

Route::resource('/facility', 'FacilityController');
Route::get('/facilitys', 'FacilityController@list')->name('facilitys');

// ---------------------------- API services ----------------------------
/* servicings/value/field */
Route::get('/servicing/servicings/{id}/{name}', 'ServicingController@servicings')->name('servicings');

//services list Routes
Route::get('/servicing/new', 'ServicingController@new')->name('new');
Route::get('/servicing/create_new', 'ServicingController@new_create')->name('new.create');
Route::get('/servicing/show_new/{id}', 'ServicingController@new_show')->name('new.show');
Route::put('/servicing/update_new/{id}', 'ServicingController@new_update')->name('new.update');
Route::get('/servicing/edit_new/{id}', 'ServicingController@new_edit')->name('new.edit');
Route::get('/servicing/verify_new/{id}', 'ServicingController@new_verify')->name('new.verify');
Route::get('/servicing/news/', 'ServicingController@news')->name('news');
Route::post('/servicing/store_new', 'ServicingController@new_store')->name('new.store');
Route::delete('/servicing/delete_new/{id}', 'ServicingController@new_delete')->name('new.delete');

// services process list route
Route::get('/servicing/process_service', 'ServicingController@process_service')->name('process_service');
Route::get('/servicing/process_services', 'ServicingController@process_services')->name('process_services');
Route::get('/servicing/process_verify/{id}', 'ServicingController@process_verify')->name('process.verify');

// services done list route
Route::get('/servicing/done_service', 'ServicingController@done_service')->name('done_service');
Route::get('/servicing/done_services', 'ServicingController@done_services')->name('done_services');

// counter notify services
Route::get('/servicing/counter_services/{name}', 'ServicingController@counter_services')->name('counter_services');

Route::prefix('potency')->group(function(){
  Route::resource('criteria', 'CriteriaController');
  Route::get('/criteria/branch/{id}', 'CriteriaController@branch')->name('criteria.branch');
  Route::post('/criteria/store_new', 'CriteriaController@new_store')->name('criteria.store_new');  
  Route::get('/criteria/detail_tabulations/{id}', 'CriteriaController@detail_tabulations')->name('criteria.detail_tabulations');  
});

// PRODUK HUKUM
Route::resource('/juristical', 'JuristicalController')->except(['destroy', 'show']);
Route::get('/juristicals', 'JuristicalController@list')->name('juristicals');

// E-NIAGA
Route::prefix('eniaga')->group(function(){});

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $table = 'galleries';
    protected $guarded = [];
    protected $fillable = [];
    // protected $hidden = [];

    public function contents()
    {
        return $this->hasMany('App\Content', 'gallery_id', 'id');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function type()
    {
        return $this->belongsTo('App\Type');
    }

    public function tags()
	{
		return $this->morphToMany(Tag::class, 'taggable');
	}
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use App\Gallery;
use App\Content;
use App\Tag;
use App\Type;
use Carbon\Carbon;

class GalleryController extends Controller
{
    private $allowedImage = [
        'image/jpeg',
        'image/png',
    ];

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $content = $request->content;        
        return view('galleries.index', compact('content'));
    }

    public function create(Request $request)
    {
        // dd($request);
        $types           = Type::all();
        $tags            = Tag::select('id', 'name')->get();
        $request_content = $request->content;
        return view('galleries.create', compact('tags','types','request_content'));
    }

    public function edit($request,$id)
    {
        $types           = Type::all();
        $tags            = Tag::select('id', 'name')->get();
        $request_content = $request;
        $data            = Gallery::findOrFail($id);
        // dd($data->content);
        if($data->content == 'photo'){
            $contents = $data
                ->contents()
                ->select(['name','image'])
                ->get();
        }else{
            $contents = $data
                ->contents()
                ->select(['name','video'])
                ->get();
        }

        $data_detail = collect([
            'name' => $data->name,
            'date' => $data->updated_at->format('d-m-Y'),
            'type' => $data->type->name,
            'tags' => $data->tags->pluck('name'),
            'content'  => $data->content,
            'contents' => $contents,
        ]);

        // dd($data_detail['contents'][0]);

        return view('galleries.edit', compact('tags','types','request_content', 'data', 'data_detail'));
    }

    public function show(Request $request, $id)
    {
        $query = Gallery::findOrFail($id);

        if($query->content == 'photo'){
            $contents = $query
                ->contents()
                ->select(['name','image'])
                ->get();
        }else{
            $contents = $query
                ->contents()
                ->select(['name','video'])
                ->get();
        }

        $data = collect([
            'name' => $query->name,
            'date' => $query->updated_at->format('d-m-Y'),
            'type' => $query->type->name,
            'tags' => $query->tags->pluck('name'),
            'content'  => $query->content,
            'contents' => $contents,
        ]);

        return response()->json($data);
    }

    public function list($content)
    {
        $galleries = Gallery::where('content', '=', $content)
            ->orderBy('updated_at', 'desc')
            ->get();
        $data = $galleries->map(function($item){
            if($item->active !== 0){
                $active = 'checked';
            }else{
                $active = '';
            }

            return [
                'id' => $item->id,
                'type' => $item->type->name,
                'name' => $item->name,
                'active' => $active,
                'created' => $item->updated_at->format('d-m-Y')
            ];
        });
        // dd($data);
        return response()->json($data);
    }

    public function store(Request $request)
    {
        $data = $this->validate($request, [
            'type_id' => 'required',
            'name'    => 'required|max:191',
            'content' => 'required',
        ]);
        // test user
        $data['user_id'] = '2';
        $data['created_at'] = Carbon::now(); 
        $data['updated_at'] = Carbon::now();       

        if($request->active == null){
            $data['active'] = '0';
        }else{
            $data['active'] = '1';
        }

        $gallery = Gallery::insertGetId($data);
        if(!$gallery){
            return back()->with('alert-danger', 'Gallery '.$request->content.' tidak dapat di simpan.');
        }

        $count = count($request->tags);
        if($count > 0){
            $galleryId = Gallery::find($gallery);
            $galleryId->tags()->attach($request->tags);
        }
        // dd($request->tags);
        return redirect()->route('gallery.index', ['content' => $request->content])->with('success','Data Added');
    }

    public function content($request,$id)
    {   
        $contents        = Content::find($id);
        $request_content = $request;
        return view('galleries.content', compact('request_content','contents','id'));
    }    

    public function store_content(Request $request)
    {
        # code...
        $data = $this->validate($request, [
            'name'       => 'required|max:191',
            'content'    => 'required',
            'gallery_id' => 'required',
        ]);        


        if ($request->content == 'photo') {
            # code...
            $data_store = $this->validate($request, [
                'name'       => 'required|max:191',
                'image'      => 'required',
                'gallery_id' => 'required',
            ]);        

            if($request->hasFile('image')){
                $extension = $request->image->getMimeType();
                if (! in_array($extension, $this->allowedImage)) {
                    return back()->withInput()->withErrors(array('image' => 'Tipe file tidak di dukung.'));
                }else{
                    $date = date('ymdhis_');
                    $file = $request->image->getClientOriginalName();
                    $filename = $date . str_replace(' ', '_', strtolower($file));
                    $store = $request->image->storeAs('public/photos', $filename);
                    $data_store['image'] = $filename;
                }
            }
    
            $data_store['active'] = '1';
    
            $gallery = Content::insertGetId($data_store);
            if(!$gallery){
                return back()->with('alert-danger', 'Gallery '.$request->content.' tidak dapat di simpan.');
            }            
        }
        else if ($request->content == 'video') {
            # code...
            $data_store = $this->validate($request, [
                'name'       => 'required|max:191',
                'video'      => 'required',
                'gallery_id' => 'required',
            ]);                    
            $data_store['active'] = '1';            

            if (strpos($data_store['video'], 'youtube.com/watch?v=') !== false) {
                $data_store['video'] = str_replace('youtube.com/watch?v=','youtube.com/embed/',$data_store['video']);            
            }

            $gallery = Content::insertGetId($data_store);
            if(!$gallery){
                return back()->with('alert-danger', 'Gallery '.$request->content.' tidak dapat di simpan.');
            }                        
        }


        return redirect()->route('gallery.index', ['content' => $request->content])->with('success','Data Added');        
    }

    public function update(Request $request, $id)
    {
        $gallery = Gallery::find($id);

        $data = $this->validate($request, [
            'type_id' => 'required',
            'name'    => 'required|max:191',
            'content' => 'required',
        ]);
        // test user
        // $data['user_id'] = '2';

        if($request->active == null){
            $data['active'] = '0';
        }else{
            $data['active'] = '1';
        }

        if(!$gallery->tags()->sync($request->tags)){
            return back()->with('alert-danger', 'Data kategori tidak dapat di update.');
        }

        if(!$gallery->update($data)){
            return back()->with('alert-danger', 'Gallery tidak dapat di update.');
        }

        return redirect()->route('gallery.index', ['content' => $request->content])->with('alert-info', 'Gallery telah di update.');
    }
}

resources/views/galleries/content.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- TITLE -->
<section class="welcome p-t-10">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="title-5">BUAT GALLERY <span style="text-transform: uppercase;">{{$request_content}}</span></h3>
        <hr class="line-seprate">
      </div>
    </div>
  </div>
</section>
<!-- SECTION BODY -->
<section class="statistic-chart">
  <div class="container">
    <form action="{{route('gallery.store_content')}}" method="post" class="row" enctype="multipart/form-data">
      {{csrf_field()}}
      <input type="hidden" name="content" value="{{$request_content}}">
      <input type="hidden" name="gallery_id" value="{{$id}}">

    <div class="col-md-12">
        {{-- NAME --}}
        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
          <label class="form-control-label">Nama</label>
          <input type="text" name="name" placeholder="Isi Judul..." value="{{ old('name') }}" class="form-control">
          @if ($errors->has('name'))
            <small class="form-text text-danger">{{ $errors->first('name') }}</small>
          @endif
        </div>
    </div>


    @if ($request_content == 'video')
    <div class="col-md-12">
        {{-- NAME --}}
        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
          <label class="form-control-label">Link Video</label>
          <input type="text" name="video" placeholder="Link video..." value="{{ old('video') }}" class="form-control">
          @if ($errors->has('video'))
            <small class="form-text text-danger">{{ $errors->first('video') }}</small>
          @endif
        </div>
    </div>      
    @endif            

      @if ($request_content == 'photo')
      <div class="col-md-12">
        {{-- IMAGES --}}
        <div class="form-group{{ $errors->has('image') ? ' has-danger' : '' }}">
          <label class="form-control-label">Upload <span style="text-transform: lowercase;">{{$request_content}}</span></label>
          <img id="imageFile01" src="{{asset('storage\images\no-img.png')}}" class="img-fluid mx-auto d-block mb-3" alt="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
            </div>
            <div class="custom-file">
              <input 
                type="file" 
                class="custom-file-input" 
                id="inputGroupFile01" 
                name="image"
                accept="image/png, image/jpeg" 
                aria-describedby="inputGroupFileAddon01">
              <label class="custom-file-label" for="inputGroupFile01"></label>
            </div>
          </div>
          @if ($errors->has('image'))
            <small class="form-text text-danger">{{ $errors->first('image') }}</small>
          @endif
        </div>
      </div>
      @endif      

      <div class="col-md-12">
        <button type="submit" class="btn btn-outline-primary">Simpan</button>        
      </div>

    </form>
  </div>
</section>  
@endsection

@push('scripts')
<script>
  $(document).ready(function(){
    $('input[type="file"]').change(function(e) {
      var filename = e.target.files[0].name;
      $('.custom-file-label').text(filename);

      var reader = new FileReader();
      reader.onload = function (e) {
        $('#imageFile01').attr('src', e.target.result);
      }
      reader.readAsDataURL(this.files[0]);
    });
  });

//   var multi = new SlimSelect({
//     select: '#multiple-select'
//   })

//   var quill = new Quill('#body',{
//     modules: {
//       toolbar: QuilljsToolbarOptions,
//     },
//     theme: 'snow',
//     placeholder: '...'
//   });

  $('form').submit(function(e){
    cfg = {};
    cek = quill.getContents().ops;
    convert = new QuillDeltaToHtmlConverter(cek, cfg).convert();
    $('input[name="body"]').val(convert);
  });
</script>
@endpush

resources/views/galleries/create.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- TITLE -->
<section class="welcome p-t-10">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="title-5">BUAT GALLERY <span style="text-transform: uppercase;">{{$request_content}}</span></h3>
        <hr class="line-seprate">
      </div>
    </div>
  </div>
</section>
<!-- SECTION BODY -->
<section class="statistic-chart">
  <div class="container">
    <form action="{{route('gallery.store')}}" method="post" class="row" enctype="multipart/form-data">
      {{csrf_field()}}
      <input type="hidden" name="content" value="{{$request_content}}">
      <div class="col-md-6">
        {{-- NAME --}}
        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
          <label class="form-control-label">Judul</label>
          <input type="text" name="name" placeholder="Isi Judul..." value="{{ old('name') }}" class="form-control">
          @if ($errors->has('name'))
            <small class="form-text text-danger">{{ $errors->first('name') }}</small>
          @endif
        </div>
        {{-- TYPE & STATUS --}}
        <div class="row">
          <div class="form-group col-md-6">
            <label class="form-control-label">Tipe</label>
            <div class="select">
              <select name="type_id" class="form-control">
                <option selected disabled value="">Pilih Tipe</option>
                @foreach ($types as $item)
                  <option value="{{ $item->id }}">{{ $item->name }}</option>
                @endforeach
              </select>
              @if ($errors->has('type_id'))
                <small class="form-text text-danger">{{ $errors->first('type_id') }}</small>
              @endif
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-control-label">Status Aktif</div>
            <label class="switch switch-text switch-success mt-3">
              <input id="poststatus" type="checkbox" name="active" class="switch-input" checked>
              <span data-on="On" data-off="Off" class="switch-label"></span>
              <span class="switch-handle"></span>
            </label>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        {{-- TAGS --}}
        <label for="multiple-select" class=" form-control-label">Kategori</label>
        <select name="tags[]" id="multiple-select" multiple="" class="">
          @foreach($tags as $item)
            <option value="{{$item->id}}">{!! $item->name !!}</option>
          @endforeach
        </select>      
      </div>
      <div class="col-md-12">
        <button type="submit" class="btn btn-outline-primary">Simpan</button>        
      </div>

    </form>
  </div>
</section>  
@endsection

@push('scripts')
<script>
  $(document).ready(function(){
    $('input[type="file"]').change(function(e) {
      var filename = e.target.files[0].name;
      $('.custom-file-label').text(filename);

      var reader = new FileReader();
      reader.onload = function (e) {
        $('#imageFile01').attr('src', e.target.result);
      }
      reader.readAsDataURL(this.files[0]);
    });
  });

  var multi = new SlimSelect({
    select: '#multiple-select'
  })

  var quill = new Quill('#body',{
    modules: {
      toolbar: QuilljsToolbarOptions,
    },
    theme: 'snow',
    placeholder: '...'
  });

  $('form').submit(function(e){
    cfg = {};
    cek = quill.getContents().ops;
    convert = new QuillDeltaToHtmlConverter(cek, cfg).convert();
    $('input[name="body"]').val(convert);
  });
</script>
@endpush

resources/views/galleries/index.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- TITLE -->
<section class="welcome p-t-10">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="title-5 text-uppercase">DAFTAR GALERI {!!$content!!}</h3>
        <hr class="line-seprate">
      </div>
    </div>
  </div>
</section>
<!-- SECTION BODY -->
<section class="statistic-chart">
  <div class="container">
    <div class="table-responsive m-b-40">
        <div class="table-data__tool">
          <div class="table-data__tool-left">
          <a href="{{route('gallery.create', ['content' => $content])}}" class="btn btn-info mt-2 ml-5 text-capitalize">Tambah Galeri {!!$content!!}</a>
          </div>
        </div>
        {{-- <table id="posttable"> --}}
        <table id="gallerytable" class="table table-borderless table-data3">
          <thead>
            <tr>
              <th>ID</th>
              <th>tanggal</th>
              <th>tipe</th>
              <th>judul</th>
              <th>Aktif</th>
              <th>Aksi</th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>
    </div>
  </div>
</section>
<!-- MODAL VIEW -->
<div 
  class="modal fade bd-example-modal-lg" 
  id="viewModal" 
  tabindex="-1" 
  role="dialog" 
  aria-labelledby="viewModalLabel" 
  aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="viewModalLabel">Modal title</h5>
        <button type="button" class="close text-danger" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body bg-white">
        <div>
          <span>Tanggal: </span>
          <span id="viewModalDate"></span>
        </div>
        <div>
          <span>Tipe: </span>
          <span id="viewModalType"></span>
        </div>
        <div class="mb-3">
          <span>Kategory: </span>
          <span id="viewModalTags"></span>
        </div>
        <hr>
        <div id="viewModalContents" class="d-flex flex-row flex-wrap"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
@endsection

@push('scripts')
<script>
  view_content = "{!!$content!!}";
  $("#gallerytable").DataTable({
    scrollY: "320px",
    scrollCollapse: true,
    paging: false,
    ajax: {
      url: '{{ route('galleries', $content) }}',
      dataSrc: '',
    },
    order: [[ 1, "desc" ]],
    columns: [
      {data: 'id'},
      {data: 'created'},
      {data: 'type'},
      {data: 'name'},
    ],
    columnDefs: [
      {
        targets: [ 0 ],
        visible: false,
        searchable: false
      },
      {
        targets: [ 4 ],
        data: 'active',
        render: function ( data, type, row, meta ) {
          return `
            <label class="au-checkbox">
              <input type="checkbox" `+data+`>
              <span class="au-checkmark"></span>
            </label>`;
        }
      },
      {
        targets: [5],
        data: 'id',
        render: function ( data, type, row, meta ) {
          return `
            <a href="/gallery/content/`+view_content+`/`+data+`" class="btn">konten</a>          
            <a 
              href="#!" 
              class="btn view-detail" 
              data-view="`+data+`" 
              data-toggle="modal">detail</a> | 
            <a href="/gallery/edit/`+view_content+`/`+data+`" class="btn">edit</a>
          `;
        }
      }
    ]
  });
  
  $(document).on('click', '.view-detail', function(e){
    e.preventDefault();
    id = $(this).data('view');
    $.ajax({
      url: "/gallery/"+id,
      method: "GET",
      dataType: "json"
    }).done(function(res) {
      $('#viewModalLabel').text(res.name);
      $('#viewModalType').text(res.type);
      $('#viewModalDate').text(res.date);
      $('#viewModalTags').empty();
      $('#viewModalContents').empty();

      $.each(res.tags, function(i, v){
        $('#viewModalTags').append('<span class="ml-2 badge badge-info">'+v+'</span>');
      });
      
      $.each(res.contents, function(i, v){
        if(res.content == 'photo'){
          media = `
            <img 
              src="{{asset('storage/photos/`+v.image+`')}}" 
              class="card-img-top img-fluid" 
              alt="Card image cap">
          `;
        }else{
          media = `
          <div class="embed-responsive embed-responsive-16by9">
            <iframe 
              class="embed-responsive-item" 
              src="`+v.video+`" 
              allowfullscreen></iframe>
          </div>
          `;
        }
        $('#viewModalContents').append(`
          <div class="card mb-2 bg-light viewModal`+res.content+`">
            `+media+`
            <div class="card-body">
              <p class="card-text">`+v.name+`</p>
            </div>
          </div>
        `);
      });
      
      $("#viewModal").modal('show');
    }).fail(function( jqXHR, textStatus ) {
      alert( "Request failed: " + textStatus );
    });
  });
</script>
@endpush

@push('styles')
<style>
  .modal-content {
    background: #ffc107 !important;
  }
  .viewModalphoto {
    width: 11rem;
    margin: .07rem;
  }
  .viewModalvideo {
    width: 22rem;
    margin: .07rem;
  }
</style>
@endpush