routes/web.php
<?php
// SUB-DOMAIN E-NIAGA 
Route::domain('eniaga.'.env('APP_URL'))->group(function () {
  Route::get('/', function () {
      return view('soon');
  })->name('eniaga.index');
});
// PUBLIC ROUTES
Route::get('/', 'HomeController@index')->name('beranda');
Route::get('/struktur-organisasi', 'HomeController@struktur')->name('struktur');
Route::get('/sejarah', 'HomeController@sejarah')->name('sejarah');
Route::get('/potensi','HomeController@potensi'); 
Route::get('/artikel', 'HomeController@artikel')->name('artikel');
Route::get('/artikel/{name}', 'HomeController@lihat_artikel')->name('artikel.lihat');
Route::get('/galeri', 'HomeController@galeri')->name('galeri');
Route::get('/galeri/{content}/{name}', 'HomeController@lihat_album')->name('galeri.lihat');
Route::get('/produk-hukum/{name?}', 'HomeController@hukum')->name('produk-hukum');
Route::get('/pelayanan', 'HomeController@service')->name('pelayanan');
Route::get('/pelayanan/{name}', 'HomeController@services')->name('pelayanan.index');
Route::post('/propose_service', 'HomeController@propose_service')->name('propose_service.store');
Route::get('/infografik','HomeController@infografik');
Route::get('/apbdesa', 'HomeController@apbdesa')->name('apbdesa');
Route::get('/soon', function(){
  return view('soon');
})->name('soon');

// PUBLIC ROUTES --services--
Route::get('/pelayanan', 'HomeController@service')->name('pelayanan');
Route::get('/pelayanan/{name}', 'HomeController@services')->name('pelayanan.index');
Route::post('/propose_service', 'HomeController@propose_service')->name('propose_service.store');
Route::get('/propose_service', 'HomeController@propose_service')->name('propose_service');
Route::get('/trace_service', 'HomeController@trace_service')->name('trace_service');
Route::post('/trace_services', 'HomeController@trace_services')->name('trace_services');


Route::resource('/post', 'PostController');
Route::get('/posts', 'PostController@list')->name('posts');

Route::resource('/tag', 'TagController');
Route::resource('/apparatus', 'ApparatusController');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/{nama}', 'HomeController@show');

Route::resource('/type', 'TypeController');
Route::get('/types', 'TypeController@list')->name('types');

Route::resource('/profile', 'ProfileController');
Route::get('profil/{name}', 'ProfileController@profil');
// Route::get('profil/{name}', 'ProfileController@struktur');

Route::resource('/gallery', 'GalleryController');
Route::get('/gallery/content/{gallery}/{id}', 'GalleryController@content')->name('gallery.content');
Route::get('/galleries/{content}', 'GalleryController@list')->name('galleries');
Route::post('/gallery/store_content', 'GalleryController@store_content')->name('gallery.store_content');
Route::get('/gallery/edit/{gallery}/{id}', 'GalleryController@edit')->name('gallery.edit');
Route::put('/gallery/update/{id}', 'GalleryController@update')->name('gallery.update');

Route::resource('/population', 'PopulationController');
Route::get('/population/list/{id}', 'PopulationController@list')->name('populations.list');
Route::get('/populations', 'PopulationController@list')->name('populations');
Route::post('/population/get_population/{id}', 'ServicingController@get_population')->name('get_population');

Route::resource('/education', 'EducationController');
Route::get('/educations', 'EducationController@list')->name('educations');

Route::resource('/occupation', 'OccupationController');
Route::get('/occupations', 'OccupationController@list')->name('occupations');

Route::resource('/facility', 'FacilityController');
Route::get('/facilitys', 'FacilityController@list')->name('facilitys');

// ---------------------------- API services ----------------------------
/* servicings/value/field */
Route::get('/servicing/servicings/{id}/{name}', 'ServicingController@servicings')->name('servicings');

//services list Routes
Route::get('/servicing/new', 'ServicingController@new')->name('new');
Route::get('/servicing/create_new', 'ServicingController@new_create')->name('new.create');
Route::get('/servicing/show_new/{id}', 'ServicingController@new_show')->name('new.show');
Route::put('/servicing/update_new/{id}', 'ServicingController@new_update')->name('new.update');
Route::get('/servicing/edit_new/{id}', 'ServicingController@new_edit')->name('new.edit');
Route::get('/servicing/verify_new/{id}', 'ServicingController@new_verify')->name('new.verify');
Route::get('/servicing/news/', 'ServicingController@news')->name('news');
Route::post('/servicing/store_new', 'ServicingController@new_store')->name('new.store');
Route::delete('/servicing/delete_new/{id}', 'ServicingController@new_delete')->name('new.delete');

// services process list route
Route::get('/servicing/process_service', 'ServicingController@process_service')->name('process_service');
Route::get('/servicing/process_services', 'ServicingController@process_services')->name('process_services');
Route::get('/servicing/process_verify/{id}', 'ServicingController@process_verify')->name('process.verify');

// services done list route
Route::get('/servicing/done_service', 'ServicingController@done_service')->name('done_service');
Route::get('/servicing/done_services', 'ServicingController@done_services')->name('done_services');

// counter notify services
Route::get('/servicing/counter_services/{name}', 'ServicingController@counter_services')->name('counter_services');

Route::prefix('potency')->group(function(){
  Route::resource('criteria', 'CriteriaController');
  Route::get('/criteria/branch/{id}', 'CriteriaController@branch')->name('criteria.branch');
  Route::post('/criteria/store_new', 'CriteriaController@new_store')->name('criteria.store_new');  
  Route::get('/criteria/detail_tabulations/{id}', 'CriteriaController@detail_tabulations')->name('criteria.detail_tabulations');  
});

// PRODUK HUKUM
Route::resource('/juristical', 'JuristicalController')->except(['destroy', 'show']);
Route::get('/juristicals', 'JuristicalController@list')->name('juristicals');

// E-NIAGA
Route::prefix('eniaga')->group(function(){});

app/Population.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Population extends Model
{
    protected $table = 'populations';
    protected $guarded = [];
    protected $fillable = [];
    // protected $hidden = [];

    public function education()
    {
        return $this->belongsTo('App\Education');
    }

    public function occupation()
    {
        return $this->belongsTo('App\Occupation');
    }

    public function servicings()
    {
        return $this->belongsToMany('App\Servicing');
    }

    public function familiars()
    {
        return $this->hasMany(Familiar::class);
    }

    public function gender()
    {
        return array(
                        'L' => 'Laki-Laki',
                        'P' => 'Perempuan' 
                    );
    }    
}

app/Http/Controllers/PopulationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Population;
use App\Education;
use App\Occupation;

class PopulationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['list']);
    }
    
    public function index()
    {
        // $this->list();
        return view('populations.index');
    }

    public function show()
    {
        //
    }

    public function list($id=NULL)
    {
        # code...
        // dd($id);
        $population = "";
        if ($id != NULL) {
            # code...
            $population = Population::where('id', $id)->get();            
        }
        else
        {
            $population = Population::orderBy('updated_at', 'desc')->get();
        }

        $data       = $population->map(function($item){
                        $i = 1;
                        if($item->active !== 0){
                            $active = 'checked';
                        }else{
                            $active = '';
                        }
                        return [
                            'id'                       => $item->id,
                            'number_'                  => $i++,
                            'nik'                      => $item->nik,
                            'name'                     => $item->name,
                            'gender'                   => $item->gender,
                            'birthplace_and_birthdate' => $item->birthplace.','.date("d-m-Y", strtotime($item->birthdate)),
                            'bloodtype'                => $item->bloodtype,
                            'religion'                 => $item->religion,
                            'status'                   => $item->status,
                            'education'                => $item->education->name,
                            'occupation'               => $item->occupation->name,
                            'active'                   => $active,
                            'created'                  => $item->updated_at->format('d-m-Y')
                        ];
                    });

        // dd($data);                                
        return response()->json($data);
    }

    public function create()
    {
        $edu      = Education::select('id', 'name')->get();
        $occu     = Occupation::select('id', 'name')->get();
        $gender   = $this->gender();
        $religion = $this->religion();
        $status   = $this->status_nikah();
        // dd($gender[0]['id']);
        return view('populations.create', compact('edu', 'occu', 'gender', 'religion', 'status'));
    }
    
    public function gender()
    {
        return array(
                        array(
                            'id'   => 'L',
                            'name' => 'Laki-Laki'
                        ),
                        array(
                            'id'   => 'P',
                            'name' => 'Perempuan'
                        )                        
                    );
    }        

    public function religion()
    {
        return array(
                        array(
                            'id'   => 'Islam',
                            'name' => 'Islam'
                        ),
                        array(
                            'id'   => 'Kristen Protestan',
                            'name' => 'Kristen Protestan'
                        ),
                        array(
                            'id'   => 'Kristen Katolik',
                            'name' => 'Kristen Katolik'
                        ),
                        array(
                            'id'   => 'Hindu',
                            'name' => 'Hindu'
                        ),
                        array(
                            'id'   => 'Buddha',
                            'name' => 'Buddha'
                        ),
                        array(
                            'id'   => 'Kepercayaan Lainnya',
                            'name' => 'Kepercayaan Lainnya'
                        )                        
                    );
    }        
    
    public function status_nikah()
    {
        return array(
                        array(
                            'id'   => 'Kawin',
                            'name' => 'Kawin'
                        ),
                        array(
                            'id'   => 'Belum Kawin',
                            'name' => 'Belum Kawin'
                        ),
                        array(
                            'id'   => 'Cerai Hidup',
                            'name' => 'Cerai Hidup'
                        )                        
                    );
    }            

    public function store(Request $request)
    {
        // dd($request);
        $data = $this->validate($request,[
            'nik'           => 'required',
            'name'          => 'required',
            'gender'        => 'required',
            'birthplace'    => 'required',
            'birthdate'     => 'required',
            'bloodtype'     => 'required',
            'religion'      => 'required',
            'status'        => 'required',
            'nik'           => 'required',
            'education_id'  => 'required',
            'occupation_id' => 'required'
        ]);

        $data['birthdate'] = date('Y-m-d' , strtotime($data['birthdate']));

        if($request->active == null){
            $data['active'] = '0';
        }else{
            $data['active'] = '1';
        }

        Population::create($data);
        return redirect()->route('population.index')->with('success','Data Added');
    }    

    public function edit($id)
    {
        $data     = Population::findOrFail($id);
        $edu      = Education::select('id', 'name')->get();
        $occu     = Occupation::select('id', 'name')->get();
        $gender   = $this->gender();
        $religion = $this->religion();
        $status   = $this->status_nikah();
        // dd($gender[0]['id']);
        return view('populations.edit', compact('data','edu', 'occu', 'gender', 'religion', 'status'));
    }    

    public function update(Request $request, $id)
    {
        $query = $this->validate($request,[
            'nik'           => 'required',
            'name'          => 'required',
            'gender'        => 'required',
            'birthplace'    => 'required',
            'birthdate'     => 'required',
            'bloodtype'     => 'required',
            'religion'      => 'required',
            'status'        => 'required',
            'nik'           => 'required',
            'education_id'  => 'required',
            'occupation_id' => 'required'
        ]);

        $query['birthdate'] = date('Y-m-d' , strtotime($query['birthdate']));

        if($request->active == null){
            $query['active'] = '0';
        }else{
            $query['active'] = '1';
        }

        Population::find($id)->update($query);        
        return redirect()->route('population.index')->with('success','Data Updated');
    }    

    public function get_population($id)
    {
        # code...
        $this->list($id);
    }
}

resources/views/populations/create.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- TITLE -->
<section class="welcome p-t-10">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="title-5">BUAT PENDUDUK</h3>
        <hr class="line-seprate">
      </div>
    </div>
  </div>
</section>
<!-- SECTION BODY -->
<section class="statistic-chart">
    <div class="container">
        <form action="{{route('population.store')}}" method="post" class="row" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="col-md-6">
                {{-- NIK --}}
                <div class="form-group{{ $errors->has('nik') ? ' has-danger' : '' }}">
                    <label class="form-control-label">NIK</label>
                    <input type="text" name="nik" placeholder="NIK" value="{{ old('nik') }}" class="form-control">
                    @if ($errors->has('nik'))
                        <small class="form-text text-danger">{{ $errors->first('nik') }}</small>
                    @endif
                </div>

                {{-- NAME --}}
                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                    <label class="form-control-label">Nama</label>
                    <input type="text" name="name" placeholder="Nama" value="{{ old('name') }}" class="form-control">
                    @if ($errors->has('name'))
                        <small class="form-text text-danger">{{ $errors->first('name') }}</small>
                    @endif
                </div>                

                <div class="form-group">
                    <label class="form-control-label">Jenis Kelamin</label>
                    <div class="select">
                        <select name="gender" class="form-control">
                            <option selected disabled value="">Pilih Jenis Kelamin</option>
                            @foreach ($gender as $item)
                            <option value="{{ $item['id'] }}">{{ $item['name'] }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('gender'))
                            <small class="form-text text-danger">{{ $errors->first('gender') }}</small>
                        @endif
                    </div>
                </div>

                {{-- birthplace --}}
                <div class="form-group{{ $errors->has('birthplace') ? ' has-danger' : '' }}">
                    <label class="form-control-label">Tempat Lahir</label>
                    <input type="text" name="birthplace" placeholder="Tempat Lahir" value="{{ old('birthplace') }}" class="form-control">
                    @if ($errors->has('birthplace'))
                        <small class="form-text text-danger">{{ $errors->first('birthplace') }}</small>
                    @endif
                </div>                                                

                {{-- birthdate --}}
                <div class="form-group{{ $errors->has('birthdate') ? ' has-danger' : '' }}">
                    <label class="form-control-label">Tanggal Lahir</label>
                    <input type="text" name="birthdate" placeholder="Tanggal Lahir" value="{{ old('birthdate') }}" class="form-control datepicker">
                    @if ($errors->has('birthdate'))
                        <small class="form-text text-danger">{{ $errors->first('birthdate') }}</small>
                    @endif
                </div>                                                                

                {{-- bloodtype --}}
                <div class="form-group{{ $errors->has('bloodtype') ? ' has-danger' : '' }}">
                    <label class="form-control-label">Golongan Darah</label>
                    <input type="text" name="bloodtype" placeholder="Golongan Darah" value="{{ old('bloodtype') }}" class="form-control">
                    @if ($errors->has('bloodtype'))
                        <small class="form-text text-danger">{{ $errors->first('bloodtype') }}</small>
                    @endif
                </div>

            </div>
            <div class="col-md-6">
            <div class="form-group">
                    <label class="form-control-label">Agama</label>
                    <div class="select">
                        <select name="religion" class="form-control">
                            <option selected disabled value="">Pilih Agama</option>
                            @foreach ($religion as $item)
                            <option value="{{ $item['id'] }}">{{ $item['name'] }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('religion'))
                            <small class="form-text text-danger">{{ $errors->first('religion') }}</small>
                        @endif
                    </div>
                </div>                                                

                <div class="form-group">
                    <label class="form-control-label">Status</label>
                    <div class="select">
                        <select name="status" class="form-control">
                            <option selected disabled value="">Pilih Status</option>
                            @foreach ($status as $item)
                            <option value="{{ $item['id'] }}">{{ $item['name'] }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('status'))
                            <small class="form-text text-danger">{{ $errors->first('status') }}</small>
                        @endif
                    </div>
                </div>                 

                <div class="form-group">
                    <label class="switch switch-text switch-success mt-3">
                    <input id="poststatus" type="checkbox" name="active" class="switch-input" checked>
                    <span data-on="On" data-off="Off" class="switch-label"></span>
                    <span class="switch-handle"></span>
                    </label>
                </div>                                                               


                <div class="form-group">
                    <label class="form-control-label">Pendidikan</label>
                    <div class="select">
                        <select name="education_id" class="form-control">
                            <option selected disabled value="">Pilih Pendidikan</option>
                            @foreach ($edu as $item)
                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('education_id'))
                            <small class="form-text text-danger">{{ $errors->first('education_id') }}</small>
                        @endif
                    </div>
                </div>                

                <div class="form-group">
                    <label class="form-control-label">Pekerjaan</label>
                    <div class="select">
                        <select name="occupation_id" class="form-control">
                            <option selected disabled value="">Pilih Pekerjaan</option>
                            @foreach ($occu as $item)
                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('occupation_id'))
                            <small class="form-text text-danger">{{ $errors->first('occupation_id') }}</small>
                        @endif
                    </div>
                </div>                
            </div>
            <button type="submit" class="btn btn-outline-primary">Simpan</button>
        </form>
    </div>
</section>  
@endsection

@push('scripts')
<script>
    $('.datepicker').datepicker({
        maxDate: new Date,
        format: 'dd-mm-yyyy',
        todayHighlight: true,
        daysOfWeekHighlighted: "0,6"        
    });     
</script>
@endpush

resources/views/populations/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- TITLE -->
<section class="welcome p-t-10">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="title-5">EDIT PENDUDUK</h3>
        <hr class="line-seprate">
      </div>
    </div>
  </div>
</section>
<!-- SECTION BODY -->
<section class="statistic-chart">
    <div class="container">
        <form action="{{route('population.update', $data->id)}}" method="post" class="row" enctype="multipart/form-data">
        {{csrf_field()}}
        <input type="hidden" name="_method" value="PUT">
            <div class="col-md-6">
                {{-- NIK --}}
                <div class="form-group{{ $errors->has('nik') ? ' has-danger' : '' }}">
                    <label class="form-control-label">NIK</label>
                    <input type="text" name="nik" placeholder="NIK" value="{{ old('nik', $data->nik) }}" class="form-control">
                    @if ($errors->has('nik'))
                        <small class="form-text text-danger">{{ $errors->first('nik') }}</small>
                    @endif
                </div>

                {{-- NAME --}}
                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                    <label class="form-control-label">Nama</label>
                    <input type="text" name="name" placeholder="Nama" value="{{ old('name', $data->name) }}" class="form-control">
                    @if ($errors->has('name'))
                        <small class="form-text text-danger">{{ $errors->first('name') }}</small>
                    @endif
                </div>                

                <div class="form-group">
                    <label class="form-control-label">Jenis Kelamin</label>
                    <div class="select">
                        <select name="gender" class="form-control">
                            <option selected disabled value="">Pilih Jenis Kelamin</option>
                            @foreach ($gender as $item)
                            <option {{ $data->gender == $item['id'] ? 'selected' : '' }} value="{{ $item['id'] }}">{{ $item['name'] }}</option>                            
                            @endforeach
                        </select>
                        @if ($errors->has('gender'))
                            <small class="form-text text-danger">{{ $errors->first('gender') }}</small>
                        @endif
                    </div>
                </div>

                {{-- birthplace --}}
                <div class="form-group{{ $errors->has('birthplace') ? ' has-danger' : '' }}">
                    <label class="form-control-label">Tempat Lahir</label>
                    <input type="text" name="birthplace" placeholder="Tempat Lahir" value="{{ old('birthplace', $data->birthplace) }}" class="form-control">
                    @if ($errors->has('birthplace'))
                        <small class="form-text text-danger">{{ $errors->first('birthplace') }}</small>
                    @endif
                </div>                                                

                {{-- birthdate --}}
                <div class="form-group{{ $errors->has('birthdate') ? ' has-danger' : '' }}">
                    <label class="form-control-label">Tanggal Lahir</label>
                    <input type="text" name="birthdate" placeholder="Tanggal Lahir" value="{{ old('birthdate', $data->birthdate) }}" class="form-control datepicker">
                    @if ($errors->has('birthdate'))
                        <small class="form-text text-danger">{{ $errors->first('birthdate') }}</small>
                    @endif
                </div>                                                                

                {{-- bloodtype --}}
                <div class="form-group{{ $errors->has('bloodtype') ? ' has-danger' : '' }}">
                    <label class="form-control-label">Golongan Darah</label>
                    <input type="text" name="bloodtype" placeholder="Golongan Darah" value="{{ old('bloodtype', $data->bloodtype) }}" class="form-control">
                    @if ($errors->has('bloodtype'))
                        <small class="form-text text-danger">{{ $errors->first('bloodtype') }}</small>
                    @endif
                </div>

            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="form-control-label">Agama</label>
                    <div class="select">
                        <select name="religion" class="form-control">
                            <option selected disabled value="">Pilih Agama</option>
                            @foreach ($religion as $item)
                            <option value="{{ $item['id'] }}">{{ $item['name'] }}</option>
                            <option {{ $data->religion == $item['id'] ? 'selected' : '' }} value="{{ $item['id'] }}">{{ $item['name'] }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('religion'))
                            <small class="form-text text-danger">{{ $errors->first('religion') }}</small>
                        @endif
                    </div>
                </div>                                                

                <div class="form-group">
                    <label class="form-control-label">Status</label>
                    <div class="select">
                        <select name="status" class="form-control">
                            <option selected disabled value="">Pilih Status</option>
                            @foreach ($status as $item)
                            <option {{ $data->status == $item['id'] ? 'selected' : '' }} value="{{ $item['id'] }}">{{ $item['name'] }}</option>                            
                            @endforeach
                        </select>
                        @if ($errors->has('status'))
                            <small class="form-text text-danger">{{ $errors->first('status') }}</small>
                        @endif
                    </div>
                </div>                 

                <div class="form-group">
                    <label class="form-control-label">Pendidikan</label>
                    <div class="select">
                        <select name="education_id" class="form-control">
                            <option selected disabled value="">Pilih Pendidikan</option>
                            @foreach ($edu as $item)
                            <option {{ $data->education_id == $item->id ? 'selected' : '' }} value="{{ $item->id }}">{{ $item->name }}</option>                            
                            @endforeach
                        </select>
                        @if ($errors->has('education_id'))
                            <small class="form-text text-danger">{{ $errors->first('education_id') }}</small>
                        @endif
                    </div>
                </div>                

                <div class="form-group">
                    <label class="form-control-label">Pekerjaan</label>
                    <div class="select">
                        <select name="occupation_id" class="form-control">
                            <option selected disabled value="">Pilih Pekerjaan</option>
                            @foreach ($occu as $item)
                            <option {{ $data->occupation_id == $item->id ? 'selected' : '' }} value="{{ $item->id }}">{{ $item->name }}</option>                            
                            @endforeach
                        </select>
                        @if ($errors->has('occupation_id'))
                            <small class="form-text text-danger">{{ $errors->first('occupation_id') }}</small>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <label class="switch switch-text switch-success mt-3">
                        <input type="checkbox" name="active" value="{{$data->active}}" class="switch-input" {{$data->active == true ? 'checked' : ''}}>
                        <span data-on="On" data-off="Off" class="switch-label"></span>
                        <span class="switch-handle"></span>
                    </label>
                </div>
            </div>

            <div class="col-md-12">
                <button type="submit" class="btn btn-outline-primary">Simpan</button>                                                
            </div>
        </form>
    </div>
</section>  
@endsection

@push('scripts')
<script>
    $('.datepicker').datepicker({
        maxDate: new Date,
        format: 'dd-mm-yyyy',
        todayHighlight: true,
        daysOfWeekHighlighted: "0,6"        
    });    
</script>
@endpush