routes/web.php
<?php
// SUB-DOMAIN E-NIAGA 
Route::domain('eniaga.'.env('APP_URL'))->group(function () {
  Route::get('/', function () {
      return view('soon');
  })->name('eniaga.index');
});
// PUBLIC ROUTES
Route::get('/', 'HomeController@index')->name('beranda');
Route::get('/struktur-organisasi', 'HomeController@struktur')->name('struktur');
Route::get('/sejarah', 'HomeController@sejarah')->name('sejarah');
Route::get('/potensi','HomeController@potensi'); 
Route::get('/artikel', 'HomeController@artikel')->name('artikel');
Route::get('/artikel/{name}', 'HomeController@lihat_artikel')->name('artikel.lihat');
Route::get('/galeri', 'HomeController@galeri')->name('galeri');
Route::get('/galeri/{content}/{name}', 'HomeController@lihat_album')->name('galeri.lihat');
Route::get('/produk-hukum/{name?}', 'HomeController@hukum')->name('produk-hukum');
Route::get('/pelayanan', 'HomeController@service')->name('pelayanan');
Route::get('/pelayanan/{name}', 'HomeController@services')->name('pelayanan.index');
Route::post('/propose_service', 'HomeController@propose_service')->name('propose_service.store');
Route::get('/infografik','HomeController@infografik');
Route::get('/apbdesa', 'HomeController@apbdesa')->name('apbdesa');
Route::get('/soon', function(){
  return view('soon');
})->name('soon');

// PUBLIC ROUTES --services--
Route::get('/pelayanan', 'HomeController@service')->name('pelayanan');
Route::get('/pelayanan/{name}', 'HomeController@services')->name('pelayanan.index');
Route::post('/propose_service', 'HomeController@propose_service')->name('propose_service.store');
Route::get('/propose_service', 'HomeController@propose_service')->name('propose_service');
Route::get('/trace_service', 'HomeController@trace_service')->name('trace_service');
Route::post('/trace_services', 'HomeController@trace_services')->name('trace_services');


Route::resource('/post', 'PostController');
Route::get('/posts', 'PostController@list')->name('posts');

Route::resource('/tag', 'TagController');
Route::resource('/apparatus', 'ApparatusController');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/{nama}', 'HomeController@show');

Route::resource('/type', 'TypeController');
Route::get('/types', 'TypeController@list')->name('types');

Route::resource('/profile', 'ProfileController');
Route::get('profil/{name}', 'ProfileController@profil');
// Route::get('profil/{name}', 'ProfileController@struktur');

Route::resource('/gallery', 'GalleryController');
Route::get('/gallery/content/{gallery}/{id}', 'GalleryController@content')->name('gallery.content');
Route::get('/galleries/{content}', 'GalleryController@list')->name('galleries');
Route::post('/gallery/store_content', 'GalleryController@store_content')->name('gallery.store_content');
Route::get('/gallery/edit/{gallery}/{id}', 'GalleryController@edit')->name('gallery.edit');
Route::put('/gallery/update/{id}', 'GalleryController@update')->name('gallery.update');

Route::resource('/population', 'PopulationController');
Route::get('/population/list/{id}', 'PopulationController@list')->name('populations.list');
Route::get('/populations', 'PopulationController@list')->name('populations');
Route::post('/population/get_population/{id}', 'ServicingController@get_population')->name('get_population');

Route::resource('/education', 'EducationController');
Route::get('/educations', 'EducationController@list')->name('educations');

Route::resource('/occupation', 'OccupationController');
Route::get('/occupations', 'OccupationController@list')->name('occupations');

Route::resource('/facility', 'FacilityController');
Route::get('/facilitys', 'FacilityController@list')->name('facilitys');

// ---------------------------- API services ----------------------------
/* servicings/value/field */
Route::get('/servicing/servicings/{id}/{name}', 'ServicingController@servicings')->name('servicings');

//services list Routes
Route::get('/servicing/new', 'ServicingController@new')->name('new');
Route::get('/servicing/create_new', 'ServicingController@new_create')->name('new.create');
Route::get('/servicing/show_new/{id}', 'ServicingController@new_show')->name('new.show');
Route::put('/servicing/update_new/{id}', 'ServicingController@new_update')->name('new.update');
Route::get('/servicing/edit_new/{id}', 'ServicingController@new_edit')->name('new.edit');
Route::get('/servicing/verify_new/{id}', 'ServicingController@new_verify')->name('new.verify');
Route::get('/servicing/news/', 'ServicingController@news')->name('news');
Route::post('/servicing/store_new', 'ServicingController@new_store')->name('new.store');
Route::delete('/servicing/delete_new/{id}', 'ServicingController@new_delete')->name('new.delete');

// services process list route
Route::get('/servicing/process_service', 'ServicingController@process_service')->name('process_service');
Route::get('/servicing/process_services', 'ServicingController@process_services')->name('process_services');
Route::get('/servicing/process_verify/{id}', 'ServicingController@process_verify')->name('process.verify');

// services done list route
Route::get('/servicing/done_service', 'ServicingController@done_service')->name('done_service');
Route::get('/servicing/done_services', 'ServicingController@done_services')->name('done_services');

// counter notify services
Route::get('/servicing/counter_services/{name}', 'ServicingController@counter_services')->name('counter_services');

Route::prefix('potency')->group(function(){
  Route::resource('criteria', 'CriteriaController');
  Route::get('/criteria/branch/{id}', 'CriteriaController@branch')->name('criteria.branch');
  Route::post('/criteria/store_new', 'CriteriaController@new_store')->name('criteria.store_new');  
  Route::get('/criteria/detail_tabulations/{id}', 'CriteriaController@detail_tabulations')->name('criteria.detail_tabulations');  
});

// PRODUK HUKUM
Route::resource('/juristical', 'JuristicalController')->except(['destroy', 'show']);
Route::get('/juristicals', 'JuristicalController@list')->name('juristicals');

// E-NIAGA
Route::prefix('eniaga')->group(function(){});

app/Education.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Education extends Model
{
    protected $table = 'education';
    protected $guarded = [];
    protected $fillable = [];
    // protected $hidden = [];
    public $timestamps = false;
}

app/Http/Controllers/EducationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Education;

class EducationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        return view('education.index');
    }

    public function list()
    {
        $education = Education::all();
        $data      = $education->map(function($item){
            return [
                'id' => $item->id,
                'name' => $item->name
            ];
        });
        // dd($data);
        return response()->json($data);
    }    

    public function create()
    {   
        return view ('education.create');
    }    

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validate($request,[
            'name' => 'required'
        ]);
        Education::create($data);
        return redirect()->route('education.index')->with('success','Data Added');
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Education::findOrFail($id);
        return view('education.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $query = $this->validate($request,[
            'name'  => 'required'
        ]);
        
        Education::find($id)->update($query);
        // return redirect()->route('type.create')->with('success','Data Added');
        
        return redirect()->route('education.index')->with('success','Data Updated');
    }


}

resources/views/education/create.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="row">
    <div class="col-md-12">
        
        @if(count($errors)>0)
        <div class="alert alert-danger">
            <ul>
                @foreach($error->all as $error)
                <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if(\Session::has('success'))
        <div class="alert alert-success">
        <p>{{\Session::get('success')}}</p>
        </div>
        @endif

        <div class="container">
        <form method="post" action="{{url('education')}}" >
            {{csrf_field()}}    
            <div class="form-group col-md-6" >
                <br/>
                <h3 align="left">Tambah Pendidikan</h3>
                <br/>
                <input type="text" name="name" class="form-control" placeholder="Pendidikan"/>    
            </div>

            <div class="form-group col-md-6">
                <button type="submit" class="btn btn-outline-primary"> Save </button>
            </div>

            
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/education/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- TITLE -->
<section class="welcome p-t-10">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="title-5">EDIT PENDIDIKAN</h3>
                <hr class="line-seprate">
            </div>
        </div>
    </div>
</section>
<!-- SECTION BODY -->
<section class="statistic-chart">
    <div class="container">
        <form action="{{route('education.update', $data->id)}}" method="post" class="row" enctype="multipart/form-data">
            {{csrf_field()}}
            <input type="hidden" name="_method" value="PUT">
            <div class="col-md-12">
                {{-- NAME --}}
                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                <label class="form-control-label">Nama</label>
                <input type="text" name="name" placeholder="Pendidikan" value="{{ old('name', $data->name) }}" class="form-control">
                @if ($errors->has('name'))
                    <small class="form-text text-danger">{{ $errors->first('name') }}</small>
                @endif
                </div>
                <button type="submit" class="btn btn-outline-primary">Simpan</button>
            </div>
        </form>
    </div>
</section>  
@endsection

@push('scripts')
<script>  
    $(document).ready(function(){
        $('input[type="file"]').change(function(e) {
            var filename = e.target.files[0].name;
            $('.custom-file-label').text(filename);

            var reader = new FileReader();
            reader.onload = function (e) {
                $('#imageFile01').attr('src', e.target.result);
            }
            reader.readAsDataURL(this.files[0]);
        });
    });

    var multi = new SlimSelect({
        select: '#multiple-select'
    })
    
    var quill = new Quill('#body',{
        modules: {
        toolbar: QuilljsToolbarOptions
        },
        theme: 'snow',
        placeholder: '...'
    });

    content = $("#body").find(".ql-editor p").html();
    if(isJson(content) == true){
        quill.setContents(JSON.parse(quill.getContents().ops[0].insert))
    }

    $('form').submit(function(e){
        cfg = {};
        cek = quill.getContents().ops;
        convert = new QuillDeltaToHtmlConverter(cek, cfg).convert();
        $('input[name="body"]').val(convert);
    });
</script>
@endpush

resources/views/education/index.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- TITLE -->
<section class="welcome p-t-10">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="title-5">Master Pendidikan</h3>
        <hr class="line-seprate">
      </div>
    </div>
  </div>
</section>
<!-- SECTION BODY -->
<section class="statistic-chart">
  <div class="container">
    <div class="row">
      <!-- DATA TABLE-->  
      <div class="col-md-12">
        <div class="table-responsive m-b-40">
          <div class="table-data__tool">
            <div class="table-data__tool-left">
            <a href="{{route('education.create')}}" class="btn btn-info mt-2 ml-5">Tambah Pendidikan</a>
            </div>
          </div>
          {{-- <table id="educationtable"> --}}
          <table id="educationtable" class="table table-borderless table-data3">
            <thead>
              <tr>
                <th>ID</th>
                <th>Nama</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
      <!-- Button trigger modal -->
      {{-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Launch demo modal
      </button> --}}
      {{-- <canvas id="tesChart"></canvas> --}}
    </div>
  </div>
</section>
<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam laborum quas laudantium repellat? Veniam, porro voluptates accusamus aut exercitationem rem facere, tempora molestias odio quam obcaecati et, eos recusandae beatae!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consectetur, voluptate similique? Nemo delectus, quae magnam odio culpa nesciunt! Nam necessitatibus molestiae assumenda maxime odit explicabo atque ducimus placeat, repellat voluptatem?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur consectetur voluptatum alias aperiam nam impedit ea quasi optio eius, odit quisquam eveniet sunt incidunt perspiciatis sed corporis. Ducimus, quod cum.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
@endsection

@push('scripts')
<script>
  $("#educationtable").DataTable({
    scrollY: "320px",
    scrollCollapse: true,
    paging: false,
    ajax: {
      url: '{{ route('educations') }}',
      dataSrc: '',
    },
    order: [[ 0, "asc" ]],
    columns: [
      {data: 'id'},
      {data: 'name'},
    ],
    columnDefs: [
      {
        targets: [ 0 ],
        visible: false,
        searchable: false
      },
      {
        targets: [2],
        data: 'id',
        render: function ( data, type, row, meta ) {
          return '<a href="education/'+data+'/edit" class="btn">edit</a>';
        }
      }
    ]
  });

  // $('#myModal').on('shown.bs.modal', function () {
  //   $('#myInput').trigger('focus')
  // });

  // var ctx = document.getElementById("tesChart");
  // var myChart = new Chart(ctx, {});
</script>
@endpush